# Generated by Django 4.2.16 on 2024-10-22 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_alter_bannerslider_button_link'),
        ('accounts', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_name',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='myadmin.product'),
            preserve_default=False,
        ),
    ]
