# Generated by Django 4.2.16 on 2024-10-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_wishlist_product_name_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('delivery', 'Delivery'), ('billing', 'Billing')], default='delivery', max_length=10),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='addressbook',
            unique_together={('customer', 'address_type', 'is_default')},
        ),
    ]
