# Generated by Django 4.2.16 on 2024-10-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.IntegerField(choices=[(1, 'Related Product'), (2, 'Featured Product'), (3, 'Popular Product'), (4, 'Special Product')], default=1, verbose_name='Product Feature'),
        ),
    ]
