# Generated by Django 4.2.16 on 2024-10-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_bannerslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslider',
            name='button_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
